### PR TITLE
Fix infinite replace

### PR DESCRIPTION
**Pull request by monkeygroover**
See #186

I've also fixed the compile warnings

### CODE REVIEW

**Comment by Adriandmen** [comment]
Hey @monkeygroover! Thank you for taking your time to contribute to this repository!

As you may have noticed, this project is a bit outdated, and Travis CI stopped working a while ago 😅. I have pushed some changes in order to replace Travis CI with GitHub Actions. None of the affected files conflict with your PR, so just a simple rebase would most likely do the trick of getting the checks running.

I have reviewed the code and everything looks good to me. I am guessing that the changes in the other files are to resolve (deprecation) warnings. I'll approve the PR as soon as the **Build and Test** check passes.

**Comment by monkeygroover** [comment]
> I am guessing that the changes in the other files are to resolve (deprecation) warnings

yep and a couple of unused variable warnings.

Will rebase, thanks!

**Comment by monkeygroover** [comment]
> warning: the dependency :memoize requires Elixir "~> 1.9" but you are running on v1.6.4

i'll break the PR in two, can fix the deps warnings separately

**Review by Adriandmen — APPROVED** [review]
Right... this repository still uses an ancient version of Elixir and OTP.

This PR looks good to me! Approving it.

**Pull request merged**
