### PR TITLE
Default values, full vectorization and weak datatypes

### PR DESCRIPTION
**Pull request by scottinet**
# Intro

At first, all I wanted was to repair the no-input code, outputting either the documentation or a snake. Hence the branch name.

This ended up as a refactor and 150+ test cases added to test everything. 

I hope this will improve this language's already tremendous golfing capabilities!

# Description

This PR purpose is to make 05AB1E resilient against unexpected data types and empty inputs, and full vectorization has been added whenever possible.

### Weak datatypes

  * when possible, methods previously dealing only with numbers (or strings) have been extended to deal with other datatypes. For instance, the command `.x` (pop a,b=>push the element in a closest to b) previously only worked on numbers. Now, if there is at least a string in a, it falls back on string distance comparison to find the closest element
  * floats can now be fed on most functions where only ints, strings and/or lists were accepted
  * any transformation or calculation command will return the provided payload untouched if it cannot be converted to the required datatype. For instance, the program `"foo";` will output: `foo`
  * any aggregation method encountering an item of the wrong datatype will discard it. For instance, the program `12"foo"34)SO` will output `10`

### Empty inputs

On empty inputs+empty stack, commands often crash, and many times this ends up in a chain of failures, ending with an empty output.

Most of the time this pose little to no problem. But some challenges require some specific output on empty inputs, and tricking 05AB1E to make it work on such cases may sometimes require more bytes than necessary.

Now, almost all commands have a default value. Those have been set so that defaulted commands consider their default value as a neutral or empty argument, instead of receiving no argument at all.

### Full vectorization

Lots of commands are vectorized in 05AB1E, allowing them to work on any given levels of nested lists.

Some other commands were only partially vectorized, or even not at all.
Those commands are now fully vectorized.

# Boyscout

* the command  `.Ø` is no longer undocumented
* some command documentations have been either more detailed or fixed
* each command processing in `osabie.py` has now a comment with its corresponding unicode character  and documentation, to make the code more readable

# Fixed issues

#97 
#60

### CODE REVIEW

**Comment by scottinet** [comment]
*Coming soon:* an exhaustive list of changes, command by command, to make it easier to review that PR

**Comment by Adriandmen** [comment]
First of all, thank you very much for your effort 😄! I really like the changes you have made to the program. 

I did some extensive testing and had a few comments:

| Command | Review comment |
| ---------- | -------------------- |
| `Ë` | I think this might cause some problems with checking on lists of lists, like `[[1, 2], [1, 2], [1, 2]]`, which should result in `1`. The reason behind this is that you can make a vectorized version with `€Ë`, but the other way around would result in +~4-5 extra. |
| `.å` | I saw that the `.å`-command was removed. The docs are a bit weird (my apologies for that :p), but it is actually a different version than the normal `å`-command. For example: `12 23 34) 34å` results in `1`, but `12 23 34) 3.å` results in `[0, 1, 1]`. |
| `ê`/`Ù`/`Ú`/`Œ`/`.m`/`.M`/`Ô` | A problem similar with the `Ë`-command. As lists are also valid elements for the command (i.e. they don't cause any exceptions or trouble), they should be treated as such. |

Let me know if you have any questions.

**Comment by Adriandmen** [comment]
Don't worry about Code Climate, I'm still experimenting a bit with that so you can ignore that :P.

**Comment by scottinet** [comment]
You're right: the changes I made on those commands can easily be reproduced simply by deep-flattening lists beforehand (+1 byte), whereas simulating the prior behavior is much more costly.

I've started fixing these issues. I have to go to work now, I may be able to fix the remaining problems today.
I'm adding new test cases along the way.

About code climate, I'll keep an eye on it anyway. Reducing cyclomatic complexity is always a good thing  :)

**Comment by scottinet** [comment]
@Adriandmen > I took a closer look at the other commands:

## `ê` (sort+uniquify a)

I'm a bit torn about this one. The uniquify part as you describe makes complete sense to me, and I'll fix that part. For instance, `5LR;3LR5LR;)ê` should indeed return only one instance of `5LR;`.
But I have some doubts about the sorting part. I think that [this example](https://tio.run/##MzBNTDJM/f/fyCfIxEfz8Kr////rpgAA) shows better than anything else what I mean by that.
In your opinion, how should I address this?
* keep the current master branch behavior as-is, as it fits golf challenges better
* perform a vectorized sort, and then sort each sublist compared to each other (string comparison)
* sort only each list independantly (as it is done in this branch), but uniquify all lists globally afterward (in-between)

## `Ù` (uniquify), `Ú `(reverse uniquify) and `Ô` connected uniquified

Makes complete sense, will fix ASAP :+1: 

## `Œ` (substrings)

I cannot believe I let this one pass. This branch's implementation of that command is completely messed up and should not have been submitted like that. My apologies.

## `.m` (least frequent) / `.M` (most frequent)

Very interesting approach.  This will make these commands even more versatile than the way I changed them, and we can always deep-flatten `a` if we need to obtain the current implementation.  
A question though: should I consider `[1, 2]` and `[2, 1]` as 2 separate lists or as 2 occurences of the same one?

Either way, will change these two commands some more to make them able to output a list as a most/least frequent item. :+1:

**Comment by Adriandmen** [comment]
@scottinet Hmm, could you please elaborate on the sorted-uniquified part? What that command does is uniquify `a` and sorts `a` afterwards, so the TIO example you have given is correct.

**Comment by scottinet** [comment]
@Adriandmen > it took me time but I think I know exactly what my problem is: I thought that I had vectorized `{` (sort a) too. And to me, sort-uniquify should be a shortcut to `Ù{`. So in the above example, I expected the following result: `[[1, 2], [1, 2, 3, 4]]`
Obviously, since `{` is not vectorized, my point is moot.

But I think that having a vectorized sort has its uses, as do a vectorized sort + uniquify, because I don't see an easy way to get the result I expected with the current set of commands.

So I propose the following:
* I revert `ê` to make it match your description of the command
* I add the following commands:
  * `.{`: vectorized sort
  * `.ê`: vectorized + vectorized uniquify 
  * `.Ù`: vectorized uniquify (uniquify values in list, not the list themselves)

_Note:_ what I had in mind is not in the proposal list, because it could easily be obtained with `.{Ù`

What do you think?

**Comment by Adriandmen** [comment]
@scottinet Sounds great! That will definitely save some bytes when used 😄. Only one question, what is the difference between `.{` and `€{`?

**Comment by scottinet** [comment]
For-each applies a command to each element, so `€{` works if we only have lists of lists, for instance: https://tio.run/##MzBNTDJM/f/fyCfIxCdI81HTmur////rpgAA

There are two cases where it won't work:
* if there are values mixed with lists in the list to sort: https://tio.run/##MzBNTDJM/f/fyCfIxCfIWMFIwVDzUdOa6v///@umAAA . In this case, `.{` would output `[[1, 2], [1, 2, 3, 4], '1', '2', '3']`
* if there are 3 levels or more of depth. In this case the usefulness is far more debatable since I don't know if this can happen

Truth is, I forgot entirely about `€`, and I don't know if vectorizing sort and/or uniquify is really useful. 
So unless you think otherwise, the best course of action is probably to not add these commands. These can always be added at a later time if the need arises.

Thanks a lot for your patience and to take the time to consider my proposals.

**Comment by scottinet** [comment]
@Adriandmen > All done + test cases added/updated!

**Comment by Adriandmen** [comment]
@scottinet Awesome! You are the best :).

About the vectorized sorting, it is a bit weird but it could be useful. I haven't had a case where I had to use such command, because having mixed depths in the lists is very rare. Feel free to implement it if you want though, I don't see how that can negatively affect the language :).

For depth 3, we can always add another `€` like this [`€€Ù`](https://tio.run/##MzBNTDJM/f//UdMaIDo88///6OhoQx0FIyCK1VGINkJhGgNRbGwsAA), although it is indeed a byte longer :P.

Also, thanks for reducing the complexity. That is something that I always keep forgetting 😅. I'll review this right away.

**Pull request merged**
